
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 25 13:07:03 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 16;
  public static final int NUMCONST = 47;
  public static final int IMPL = 43;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 20;
  public static final int FOR = 21;
  public static final int MINUS = 25;
  public static final int STATIC = 22;
  public static final int RPAREN = 7;
  public static final int GRE = 32;
  public static final int AND = 35;
  public static final int RANGE = 45;
  public static final int IN = 44;
  public static final int OR = 36;
  public static final int COMMA = 8;
  public static final int CLASS = 15;
  public static final int INC = 37;
  public static final int DIV = 27;
  public static final int PLUS = 11;
  public static final int IF = 23;
  public static final int LSQBRACE = 41;
  public static final int DOT = 38;
  public static final int LE = 33;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int NOEQ = 30;
  public static final int EQUAL = 12;
  public static final int NEW = 17;
  public static final int error = 1;
  public static final int MUL = 26;
  public static final int IDENT = 46;
  public static final int BREAK = 14;
  public static final int VOID = 13;
  public static final int EQ = 29;
  public static final int COL = 40;
  public static final int LBRACE = 3;
  public static final int ELSE = 24;
  public static final int READ = 18;
  public static final int CHARCONST = 48;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 49;
  public static final int EXTENDS = 19;
  public static final int PROG = 2;
  public static final int PROC = 28;
  public static final int RSQBRACE = 42;
  public static final int DEC = 39;
  public static final int LEE = 34;
  public static final int GR = 31;
  public static final int PRINT = 9;
}

